config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get '/about', to: 'pages#about'
  get '/help', to: 'pages#help'
  
  
  resources :todos
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
  
  def help
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  
  def new
   @todo = Todo.new
  end 
  
  def create
    @todo = Todo.new(todo_params)
  if @todo.save
    flash[:notice] = "Item Listed succesfully"
    redirect_to todo_path(@todo)
  else render 'new'
  end
  end
  
  def show
   
  end
  
  def edit
    
  end
  
  def update
  if @todo.update(todo_params)
    flash[:notice] = "Item Listed succesfully"
    redirect_to todo_path(@todo)
  else
    render 'edit'
  end
  end
  
  def index
    @todos = Todo.all
  end
  
  def destroy
    @todo.destroy
    flash[:notice] = "Deleted successfully"
    redirect_to todos_path
  end
  
  private
  
  def set_todo
    @todo = Todo.find(params[:id])
  end
  
  def todo_params
    params.require(:todo).permit(:name, :description)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li>
      <%= msg %>
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>about page</h1>

app/views/pages/help.html.erb
<h1>Help Page</h1>

app/views/pages/home.html.erb
<h1>Hello World</h1>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
  <h3>Submit Fail</h3>
  <ul>
    <% @todo.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>
    <% end %>
  </ul>

<% end %>



<%= form_for @todo do |f|  %>

  <p>
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

<%= link_to "Lists", todos_path %>

app/views/todos/edit.html.erb
<h1>Edit List</h1>

<%= render 'form' %>

app/views/todos/index.html.erb
<h1>Listing All Items</h1>

<p>
  <%= link_to "Create a List", new_todo_path %>
</p>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  
  <% @todos.each do |items| %>
    <tr>
      <td><%= items.name %></td>
      <td><%= items.description %></td>
      <td><%= link_to "Edit", edit_todo_path(items) %></td>
      <td><%= link_to "Show", todo_path(items) %></td>
      <td><%= link_to "Delete", todo_path(items), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
</table>

app/views/todos/new.html.erb
<h1> Create List</h1>

<%= render 'form' %>

app/views/todos/show.html.erb
<h1>Showing List</h1>


    <p>
      name: <%= @todo.name %>
    </p>
    <p>
      description: <%= @todo.description %>
    </p>
    
    <%= link_to "Edit this Item", edit_todo_path(@todo) %> | 
    <%= link_to "Back to List", todos_path %>
    